# Generated by Django 3.0.1 on 2020-01-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parlour',
            old_name='parlour_decription',
            new_name='parlour_description',
        ),
    ]
